name: Github Pages
on:
  push:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: python3 -m pip install mkdocs-bootswatch 
    - name: Build main page docs
      run: |
        cd ID_software_architecture_files
        mkdocs build
        mv site ../_site
    - name: Copy shared files
      run: |
        for dir in domain nginx apache iis; do
          mkdir -p $dir/_includes
          cp _includes/head_custom.html $dir/_includes/head_custom.html
        done
    - name: Build domain page docs
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./domain
        destination: ./_site/domain
    - name: Build nginx page docs
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./nginx
        destination: ./_site/nginx
    - name: Build apache page docs
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./apache
        destination: ./_site/apache
    - name: Build iis page docs
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./iis
        destination: ./_site/iis
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
